#! /bin/bash

gcc -fPIC -g -c -Wall wrap.c -lallegro
gcc -shared -Wl,-soname,liballegro_keyboard_wrap.so.1 -o liballegro_keyboard_wrap.so.1.0.1 wrap.o -lc
sudo cp liballegro_keyboard_wrap.so.1.0.1 /usr/local/lib
rm liballegro_keyboard_wrap.so.1.0.1
rm wrap.o
