#lang racket/base

(require ffi/unsafe
         "lib.rkt")
(provide (all-defined-out))

(defallegro al-create-fs-entry : _string -> _Allegro-FS-Entry-pointer)
(defallegro al-destroy-fs-entry : _Allegro-FS-Entry-pointer -> _void)
(defallegro al-get-fs-entry-name : _Allegro-FS-Entry-pointer -> _Allegro-Path-pointer)
(defallegro al-update-fs-entry : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-get-fs-entry-mode : _Allegro-FS-Entry-pointer -> _uint32)
(defallegro al-get-fs-entry-atime : _Allegro-FS-Entry-pointer -> _time-t)
(defallegro al-get-fs-entry-ctime : _Allegro-FS-Entry-pointer -> _time-t)
(defallegro al-get-fs-entry-mtime : _Allegro-FS-Entry-pointer -> _time-t)
(defallegro al-get-fs-entry-size : _Allegro-FS-Entry-pointer -> _off-t)
(defallegro al-fs-entry-exists : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-fs-entry-is-file : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-fs-entry-is-directory : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-remove-fs-entry : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-filename-exists : _string -> _bool)
(defallegro al-remove-filename : _string -> _bool)
(defallegro al-open-directory : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-read-directory : _Allegro-FS-Entry-pointer -> _Allegro-FS-Entry-pointer)
(defallegro al-close-directory : _Allegro-FS-Entry-pointer -> _bool)
(defallegro al-get-current-directory : -> _Allegro-Path-pointer)
(defallegro al-change-directory : _string -> _bool)
(defallegro al-make-directory : _string -> _bool)
(defallegro al-set-fs-interface : _Allegro-FS-Interface-pointer -> _void)
(defallegro al-set-standard-fs-interface : _Allegro-FS-Interface-pointer -> _void)
(defallegro al-get-fs-interface : -> _Allegro-FS-Interface-pointer)