#lang racket/base

(require ffi/unsafe
         "lib.rkt")
(provide (all-defined-out))

(defallegro al-fopen : _string _string -> _Allegro-File-pointer)
(defallegro al-fclose : _Allegro-File-pointer -> _void)
(defallegro al-fread : _Allegro-File-pointer _pointer _size-t -> _size-t)
(defallegro al-fwrite : _Allegro-File-pointer _pointer _size-t -> _size-t)
(defallegro al-fflush : _Allegro-File-pointer -> _bool)
(defallegro al-ftell : _Allegro-File-pointer -> _int64)
(defallegro al-fseek : _Allegro-File-pointer _int64 _int -> _bool)
(defallegro al-feof : _Allegro-File-pointer -> _bool)
(defallegro al-ferror : _Allegro-File-pointer -> _bool)
(defallegro al-fungetc : _Allegro-File-pointer _int -> _int)
(defallegro al-fsize : _Allegro-File-pointer -> _int64)
(defallegro al-fgetc : _Allegro-File-pointer -> _int)
(defallegro al-fputc : _Allegro-File-pointer _int -> _int)
(defallegro al-fread16le : _Allegro-File-pointer -> _int16)
(defallegro al-fread16be : _Allegro-File-pointer -> _int16)
(defallegro al-fread32le : _Allegro-File-pointer -> _int32)
(defallegro al-fread32be : _Allegro-File-pointer -> _int32)
(defallegro al-fwrite16le : _Allegro-File-pointer _int16 -> _size-t)
(defallegro al-fwrite16be : _Allegro-File-pointer _int16 -> _size-t)
(defallegro al-fwrite32le : _Allegro-File-pointer _int32 -> _size-t)
(defallegro al-fwrite32be : _Allegro-File-pointer _int32 -> _size-t)
(defallegro al-fgets : _Allegro-File-pointer _string _size-t -> _string)
(defallegro al-fget-ustr : _Allegro-File-pointer -> _Allegro-Ustr-pointer)
(defallegro al-fputs : _Allegro-File-pointer _string -> _int)
(defallegro al-fopen-fd : _int _string -> _Allegro-File-pointer)
(defallegro al-make-temp-file : _string (_ptr i _Allegro-Path-pointer) -> _Allegro-File-pointer)
(defallegro al-set-new-file-interface : _Allegro-File-Interface-pointer -> _void)
(defallegro al-set-standard-file-interface : _Allegro-File-Interface-pointer -> _void)
(defallegro al-get-new-file-interface : -> _Allegro-File-Interface-pointer)