#lang racket/base

(require ffi/unsafe
         "lib.rkt")
(provide (all-defined-out))

(defallegro al-install-mouse : -> _bool)
(defallegro al-is-mouse-installed : -> _bool)
(defallegro al-uninstall-mouse : -> _void)
(defallegro al-get-mouse-num-axes : -> _uint)
(defallegro al-get-mouse-num-buttons : -> _uint)
(defallegro al-get-mouse-state : _Allegro-Mouse-State-pointer -> _void)
(defallegro al-get-mouse-state-axis : _Allegro-Mouse-State-pointer _int -> _int)
(defallegro al-mouse-button-down : _Allegro-Mouse-State-pointer _int -> _int)
(defallegro al-set-mouse-xy : _Allegro-Display-pointer _int _int -> _bool)
(defallegro al-set-mouse-z : _int -> _bool)
(defallegro al-set-mouse-w : _int -> _bool)
(defallegro al-set-mouse-axis : _int _int -> _bool)
(defallegro al-get-mouse-event-source : -> _Allegro-Event-Source-pointer)
(defallegro al-create-mouse-cursor : _Allegro-Bitmap-pointer _int _int -> _Allegro-Mouse-Cursor-pointer)
(defallegro al-destroy-mouse-cursor : _Allegro-Mouse-Cursor-pointer -> _void)
(defallegro al-set-mouse-cursor : _Allegro-Display-pointer _Allegro-Mouse-Cursor-pointer -> _bool)
(defallegro al-set-system-mouse-cursor : _Allegro-Display-pointer _Allegro-System-Mouse-Cursor -> _bool)
(defallegro al-get-mouse-cursor-position : (_ptr i _int) (_ptr i _int) -> _bool)
(defallegro al-hide-mouse-cursor : _Allegro-Display-pointer -> _bool)
(defallegro al-show-mouse-cursor : _Allegro-Display-pointer -> _bool)