#lang racket

(require ffi/unsafe
         "lib.rkt")
(provide (all-defined-out))

(defallegro al-create-path : _string -> _Allegro-Path-pointer)
(defallegro al-create-path-for-directory : _string -> _Allegro-Path-pointer)
(defallegro al-destroy-path : _Allegro-Path-pointer -> _void)
(defallegro al-clone-path : _Allegro-Path-pointer -> (_or-null _Allegro-Path-pointer))
(defallegro al-join-paths : _Allegro-Path-pointer _Allegro-Path-pointer -> _bool)
(defallegro al-get-path-drive : _Allegro-Path-pointer -> _string)
(defallegro al-get-path-num-components : _Allegro-Path-pointer -> _int)
(defallegro al-get-path-component : _Allegro-Path-pointer _int -> _string)
(defallegro al-get-path-tail : _Allegro-Path-pointer -> _string)
(defallegro al-get-path-filename : _Allegro-Path-pointer -> _string)
(defallegro al-get-path-basename : _Allegro-Path-pointer -> _string)
(defallegro al-get-path-extension : _Allegro-Path-pointer -> _string)
(defallegro al-set-path-drive : _Allegro-Path-pointer _string -> _void)
(defallegro al-append-path-component : _Allegro-Path-pointer _string -> _void)
(defallegro al-insert-path-component : _Allegro-Path-pointer _int _string -> _void)
(defallegro al-replace-path-component : _Allegro-Path-pointer _int _string -> _void)
(defallegro al-remove-path-component : _Allegro-Path-pointer _int -> _void)
(defallegro al-drop-path-tail : _Allegro-Path-pointer -> _void)
(defallegro al-set-path-filename : _Allegro-Path-pointer _string -> _void)
(defallegro al-set-path-extension : _Allegro-Path-pointer _string -> _void)
(defallegro al-path-cstr : _Allegro-Path-pointer _char -> (_ptr o _char))
(defallegro al-make-path-absolute : _Allegro-Path-pointer -> _bool)
(defallegro al-make-path-canonical : _Allegro-Path-pointer -> _bool)
(defallegro al-is-path-present : _Allegro-Path-pointer -> _bool)