#lang racket

(require racket/tcp 
         (except-in ffi/unsafe ->)
         "../vtx/module.rkt")
(provide (all-defined-out))

; given a new connection, turn into client mode by registering function pointers
; to closures that close over the tcp listener.
(define/contract (rkt:vortex-connection-set-client-mode-closures conn)
  (VortexConnection*? . -> . void)
  (define inp #f)
  (define outp #f)
  (define/contract (connect/tcp host port conn)
    (string? string? VortexConnection*? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let-values ([(in out) (tcp-connect host (string->number port))])
        (set! inp in)
        (set! outp out))
      (vortex-connection-set-socket conn 1 #f #f)
      1))
  (define/contract (read/tcp buffer buffer-len)
    (string? integer?  . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let ([res (read-string! buffer inp 0 buffer-len)])
        (if (eof-object? res) 0 res))))
  (define/contract (write/tcp buffer buffer-len)
    (string? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (write-string buffer outp 0 buffer-len)))
  (define/contract (close/tcp)
    (-> integer?)
    (with-handlers ([exn:fail:network? -1])
      (close-input-port inp)
      (close-output-port outp)
      1))
  (define/contract (getsockname/tcp local-addr* local-port* remote-addr* remote-port*)
    (cpointer? cpointer? cpointer? cpointer? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let-values ([(locala localp remotea remotep) (tcp-addresses inp #t)])
        (ptr-set! local-addr* _string locala)
        (ptr-set! local-port* _string (number->string localp))
        (ptr-set! remote-addr* _string remotea)
        (ptr-set! remote-port* _string (number->string remotep))
        1)))
  (vortex-connection-set-client-mode-closures connect/tcp read/tcp write/tcp close/tcp getsockname/tcp))

; given a new connection, turn it into listener mode by registering function pointers
; to closures that close over the tcp listener.
(define/contract (rkt:vortex-connection-set-listener-mode-closures conn)
  (VortexConnection*? . -> . void)
  (define inp #f)
  (define outp #f)
  (define listener #f)
  (define/contract (listen/tcp host port)
    (string? string? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (if (eq? host #f)
          (set! listener (tcp-listen (string->number port) 10000 #t))
          (set! listener (tcp-listen (string->number port) 10000 host)))
      1))
  (define/contract (accept/tcp conn)
    (VortexConnection*? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let-values ([(in out) (tcp-accept listener)])
        (set! inp in)
        (set! outp out))
      (vortex-connection-set-socket conn 1 #f #f)
      1))
  (define/contract (read/tcp buffer buffer-len)
    (string? integer?  . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let ([res (read-string! buffer inp 0 buffer-len)])
        (if (eof-object? res) 0 res))))
  (define/contract (write/tcp buffer buffer-len)
    (string? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (write-string buffer outp 0 buffer-len)))
  (define/contract (close/tcp)
    (-> integer?)
    (with-handlers ([exn:fail:network? -1])
      (close-input-port inp)
      (close-output-port outp)
      1))
  (define/contract (getsockname/tcp local-addr* local-port* remote-addr* remote-port*)
    (cpointer? cpointer? cpointer? cpointer? . -> . integer?)
    (with-handlers ([exn:fail:network? -1])
      (let-values ([(locala localp remotea remotep) (tcp-addresses inp #t)])
        (ptr-set! local-addr* _string locala)
        (ptr-set! local-port* _string (number->string localp))
        (ptr-set! remote-addr* _string remotea)
        (ptr-set! remote-port* _string (number->string remotep))
        1)))
  (vortex-connection-set-listener-mode-closures listen/tcp accept/tcp read/tcp write/tcp close/tcp getsockname/tcp))