#lang racket/base

(require "ws.rkt"
         racket/async-channel)

(define (open-a-tab/synch)
  (define ac (make-async-channel))
  (define (wait-for-response)
    (async-channel-get ac))  
  (define s (open-a-tab (λ (json) (async-channel-put ac json))))
  (values s wait-for-response))

(define-values (s get-last-response) (open-a-tab/synch)) 
(ui-wait-for-readiness s)

(ui-send! s (new-button "Foo"))
(get-last-response)
(ui-send! s (new-menu "File..."))
(get-last-response)
(ui-send! s (new-menu "Session..."))
(get-last-response)
(ui-send! s (new-menu-item "Unsubscribe" "File..." "alert(\"Unsubscribe pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Share sink" "File..." "alert(\"Share Sink pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Move source" "File..." "alert(\"Move Source pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Greyscale" "File..." "alert(\"Greyscale pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Vertical flip" "File..." "alert(\"Vertical Flip pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Share" "Session..."  "alert(\"Share pressed\");"))
(get-last-response)
(ui-send! s (new-menu-item "Move" "Session..." "alert(\"Move pressed\");"))
(get-last-response)
(ui-send! s (new-dropdown "ips" "ips.json"))
(get-last-response)
(ui-send! s (new-canvas "mainvideo" 500 500))
(get-last-response)